# Generated by Django 5.2.8 on 2026-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registrationrequest_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
