# Generated by Django 5.2.8 on 2025-11-26 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('area', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('processing', 'กำลังดำเนินการ'), ('resolved', 'แก้ไขแล้ว')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, choices=[('เสียง', 'เสียง'), ('ปิดทาง', 'ปิดทาง'), ('ทั้งสองอย่าง', 'ทั้งสองอย่าง'), ('อื่นๆ', 'อื่นๆ')], max_length=100, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField()),
                ('area', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='help_files/')),
                ('status', models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ'), ('done', 'ดำเนินการเสร็จสิ้น')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
