# Generated by Django 5.2.8 on 2025-12-10 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_with', models.CharField(choices=[('headman', 'ผู้ใหญ่บ้าน'), ('assistant_headman', 'ผู้ช่วยผู้ใหญ่บ้าน')], max_length=30)),
                ('meeting_place', models.CharField(choices=[('village_hall', 'ศาลากลางหมู่บ้าน'), ('temple', 'วัด'), ('headman_office', 'สถานที่ทำการผู้ใหญ่บ้าน'), ('learning_center', 'ศูนย์ให้ความรู้หมู่บ้าน')], max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('approved', 'ยืนยันนัดหมาย'), ('canceled', 'ยกเลิกโดยผู้ใช้'), ('rejected', 'ผู้ใหญ่บ้านปฏิเสธ')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
