# Generated by Django 5.2.8 on 2026-01-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_appointment_meeting_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('processing', 'กำลังดำเนินการ'), ('resolved', 'แก้ไขแล้ว'), ('canceled', 'ยกเลิกโดยผู้ใช้')], default='pending', max_length=20),
        ),
    ]
