# Generated by Django 5.2.8 on 2026-05-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthelp',
            name='status',
            field=models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ'), ('done', 'ดำเนินการเสร็จสิ้น'), ('canceled', 'ยกเลิกโดยผู้ใช้')], default='pending', max_length=20),
        ),
    ]
