# Generated by Django 5.2.8 on 2026-05-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_requesthelp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthelp',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
