# Generated by Django 5.2.8 on 2026-05-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_requesthelp_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('approved', 'ยืนยันนัดหมาย'), ('canceled', 'ยกเลิกโดยผู้ใช้'), ('rejected', 'ผู้ใหญ่บ้านปฏิเสธ'), ('done', 'ดำเนินการเสร็จสิ้น')], default='pending', max_length=20),
        ),
    ]
