# Generated by Django 5.2.8 on 2025-11-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('water', 'ตู้กดน้ำ'), ('washer', 'เครื่องซักผ้า'), ('other', 'บริการอื่นๆ')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('normal', 'ใช้งานได้ปกติ'), ('maintenance', 'กำลังซ่อมบำรุง'), ('broken', 'ชำรุด')], default='normal', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
