# Generated by Django 5.2.8 on 2025-12-14 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrow.location'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
