# Generated by Django 5.2.8 on 2026-05-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
