# Generated by Django 5.2.8 on 2026-02-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='อัตราดอกเบี้ย (%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, help_text='ดอกเบี้ยที่ระบบคำนวณให้', max_digits=12)),
                ('purpose', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='village.fundrecord')),
            ],
        ),
        migrations.AddField(
            model_name='fundrecord',
            name='fund_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='village.fundtype'),
        ),
        migrations.AddField(
            model_name='fundtype',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_types', to='village.village'),
        ),
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('leader', 'ผู้นำชุมชน'), ('committee', 'คณะกรรมการหมู่บ้าน'), ('volunteer', 'อสม.')], max_length=20)),
                ('position', models.CharField(choices=[('president', 'ประธาน'), ('vice', 'รองประธาน'), ('member', 'สมาชิก')], max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='village/profiles/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='village.village')),
            ],
        ),
        migrations.CreateModel(
            name='VillageExtraSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='village/extra/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_sections', to='village.village')),
            ],
        ),
        migrations.CreateModel(
            name='VillageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='village/history/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='village.village')),
            ],
        ),
        migrations.CreateModel(
            name='VillagePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='village/places/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='village.village')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fundrecord',
            unique_together={('fund_type', 'year')},
        ),
    ]
