# Generated by Django 5.2.8 on 2026-02-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrecord',
            name='last_uploaded_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
