# Generated by Django 5.2.8 on 2026-02-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_fundrecord_last_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityprofile',
            name='order',
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='level',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='communityprofile',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
