# Generated by Django 5.2.8 on 2026-02-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_remove_communityprofile_order_communityprofile_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
