# Generated by Django 5.2.8 on 2026-03-06 15:41

import django.db.models.deletion
import village.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0004_alter_communityprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RICH', 'Rich Content'), ('PLACES', 'Places List')], default='RICH', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='villagehistory',
            name='village',
        ),
        migrations.AlterModelOptions(
            name='villageplace',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='villageplace',
            name='description',
        ),
        migrations.RemoveField(
            model_name='villageplace',
            name='image',
        ),
        migrations.RemoveField(
            model_name='villageplace',
            name='village',
        ),
        migrations.AddField(
            model_name='villageplace',
            name='detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='VillagePlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=village.models.place_image_path)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='village.villageplace')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='villageplace',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='village.villagesection'),
        ),
        migrations.CreateModel(
            name='VillageSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=village.models.section_image_path)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='village.villagesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='VillageExtraSection',
        ),
        migrations.DeleteModel(
            name='VillageHistory',
        ),
    ]
