# Generated by Django 5.2.8 on 2026-05-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0005_villagesection_remove_villagehistory_village_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ละติจูด'),
        ),
        migrations.AddField(
            model_name='village',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ลองจิจูด'),
        ),
    ]
