# Generated by Django 5.2.8 on 2026-05-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0006_village_latitude_village_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
